// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYqCqStQxnlDuZGc3V8RJu3ytFAKNx-KM',
    appId: '1:732229664927:web:3a234c2a89be8f9afd22aa',
    messagingSenderId: '732229664927',
    projectId: 'donstep-7b0f0',
    authDomain: 'donstep-7b0f0.firebaseapp.com',
    storageBucket: 'donstep-7b0f0.firebasestorage.app',
    measurementId: 'G-3R1XCCX2L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR7YOYOpcbGzZ57BPUU8HeghmmCsIMYvo',
    appId: '1:732229664927:android:59a4a8b6812f79befd22aa',
    messagingSenderId: '732229664927',
    projectId: 'donstep-7b0f0',
    storageBucket: 'donstep-7b0f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVgt2Y4hyKgw0YEupJZGB8iUoEThku9_g',
    appId: '1:732229664927:ios:bd50551eaecf1391fd22aa',
    messagingSenderId: '732229664927',
    projectId: 'donstep-7b0f0',
    storageBucket: 'donstep-7b0f0.firebasestorage.app',
    iosBundleId: 'com.example.donstep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVgt2Y4hyKgw0YEupJZGB8iUoEThku9_g',
    appId: '1:732229664927:ios:bd50551eaecf1391fd22aa',
    messagingSenderId: '732229664927',
    projectId: 'donstep-7b0f0',
    storageBucket: 'donstep-7b0f0.firebasestorage.app',
    iosBundleId: 'com.example.donstep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYqCqStQxnlDuZGc3V8RJu3ytFAKNx-KM',
    appId: '1:732229664927:web:09105b15b7fff7a6fd22aa',
    messagingSenderId: '732229664927',
    projectId: 'donstep-7b0f0',
    authDomain: 'donstep-7b0f0.firebaseapp.com',
    storageBucket: 'donstep-7b0f0.firebasestorage.app',
    measurementId: 'G-RW47JTHK9H',
  );
}
